version: '3.8'

services:
  vulnerable-web:
    build: ./vulnerable-app
    ports:
      - "8080:5000"
    networks:
      - redlens-net

  redlens:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - vulnerable-web
    networks:
      - redlens-net
    volumes:
      - ../reports:/app/reports

networks:
  redlens-net:
    driver: bridge
